# Generated by Django 5.1.4 on 2024-12-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_news_news_image_subtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_mini_image',
            field=models.ImageField(default=0, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
