# Generated by Django 5.1.4 on 2024-12-18 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_news_news_mini_image_alter_news_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('favorite_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.news')),
            ],
        ),
    ]
